config/routes.rb
One::Application.routes.draw do
  
devise_for :users

root :to => "home#index"

resources :projects do
	resources :tracks
end

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tracks
  attr_accessible :index, :title

  accepts_nested_attributes_for :tracks  
  
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  attr_accessible :file, :index, :title, :wav
  
  validates_presence_of :project
  mount_uploader :wav, WavUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :tracks
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

	before_filter :authenticate_user!

	def index
	end

	

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

	before_filter :authenticate_user!

	def index
		@projects = Project.all
	end

	def new
		@project = Project.new
	end
	
	def create
		@project = Project.new
		@project.title = params[:project][:title]
		@project.save
		redirect_to @project
	end
	
	def show
		@project = Project.find(params[:id])
	end
	
	def edit
	end
	
	def update
	end
	
	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to(projects_path(@project))
	end
	
	

end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController

	before_filter :authenticate_user!

	def index
		@tracks = Track.all
	end
	
	def new
		@track = Track.new
		@track.project_id = params[:project_id]
	end
	
	def create
		@track = Track.new
		@track.project_id = params[:track][:project_id]
		@track.title = params[:track][:title]
		@track.wav = params[:track][:wav]
		@track.save
		redirect_to(project_path(@track.project))
	end
	
	def show
		@track = Track.find(params[:id])
	end
	
	def edit
	end
	
	def update
	end
	
	def destroy
		@track = Track.find(params[:id])
		@track.destroy
		redirect_to(project_path(@track.project))
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/track_helper.rb
module TrackHelper
end

app/views/home/index.html.erb
<h1>Multi-Track Recorder</h1>

<p>A 'multi-track recorder' is a tool that allows recording Projects to have several different layers, or tracks. I like recording</p>



<p><a href="<%= new_project_path %>">Create a new Project</a> to get started!</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Multi-Track</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<ul class="hmenu">
  		<%= render 'devise/menu/login_items' %>
	</ul>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

       

<%= yield %>

</body>
</html>

app/views/projects/create.html.erb
<h1>Created the Project!</h1>

app/views/projects/destroy.html.erb
<h1>Project Destroy</h1>

app/views/projects/edit.html.erb
<h1>Project Edit</h1>

app/views/projects/index.html.erb
<h1>Projects</h1>

<%= link_to "Start new Project", new_project_path, :class => "new_project" %>

<hr/>

<% @projects.each do |p| %>

<p><%= link_to(p.title, project_path(p)) %></p>
<h4><%= link_to 'Destroy', project_path(p),
            :confirm => 'Are you sure?', :method => :delete %></h4>

<% end %>

app/views/projects/new.html.erb
<h1>Create a new Project!</h1>

<p>Choose a suitable name for this multi-track project.</p>

<%= form_for @project do |f| %>
  <%= f.text_field :title %>
  <%= f.submit "Create" %>
<% end %>

app/views/projects/show.html.erb
<%= link_to "Go to All Projects", projects_path, :class => "all_projects" %>

<br/>


<h1><%= @project.title %></h1>

<% for track in @project.tracks %>
	<h3><%= link_to track.title, project_track_path(@project, track) %></h3>
	<h3><%= link_to 'Play', track.wav.url %></h3>
	<h4><%= link_to 'Destroy', project_track_path(@project, track),
            :confirm => 'Are you sure?', :method => :delete %></h4>	
<% end %>

<br/>

<%= link_to "Add new Track to #{@project.title}", "/projects/#{@project.id}/tracks/new", :class => "new_project_track" %>

app/views/projects/update.html.erb
<h1>Project Update</h1>

app/views/tracks/create.html.erb
<h1>You Created <%= @track.title %>!</h1>

<%= @track.inspect %>

app/views/tracks/destroy.html.erb
<h1>Track Destroyed</h1>

app/views/tracks/edit.html.erb
<h1>Track Edit</h1>

app/views/tracks/index.html.erb
<h1>Tracks Index</h1>

app/views/tracks/new.html.erb
<h1>New Track</h1>

<!--<%= params[:project_id] %>-->

<%= form_for @track, :url => { :action => "create" } do |f| %>
  <%= f.text_field :title %>
  <%= f.hidden_field :project_id %>
  <%= f.submit "Create" %>
  <%= f.file_field :wav %>
<% end %>

<a href="#" id="startrecording">Start Recording</a>
<a href="#" id="stoprecording">Stop Recording</a>

<script type="text/javascript">
	$(document).ready(function() {
		RecordPage.init(); 
	});
</script>

app/views/tracks/show.html.erb
<h1>Showing track: '<%= @track.title %>'</h1>

app/views/tracks/update.html.erb
<h1>Track Update</h1>